### ISSUE TITLE
Image labels are not rendered for new forms

### ISSUE THREAD

**Issue by eyelidlessness** [enketo/enketo-express#287] opened 2021-07-14 17:51 UTC
**Describe the bug**

Also discovered researching #218. Forms with `jr: image labels do not render after creating a new form (or after creating a new revision).

**To Reproduce**

1. Create a form (or a new revision of an existing form) with `jr:` image labels
2. Load the form

**Expected behavior**

Image labels will be rendered.

**Browser and OS (please complete the following information):**

 - OS: macOS
 - Browser: Chrome

**Additional context**

I'll be working on this following #286.

**Comment by lognaturel** [comment] 2021-07-14 23:33
Duplicate of #286 -- the issue is broadly resolving `jr://` URIs.

**Closed by lognaturel** 2021-07-14 23:33 UTC
Labels: bug, regression
