### ISSUE TITLE
Some polygons in SVG map can't be selected

### ISSUE THREAD

**Issue by enketo-issue-mover** [enketo/enketo-express#74] opened 2019-01-02 22:58 UTC
_From @tinok on November 16, 2018 21:3_

When testing the demo form for the SVG question type, some US states (RI, KY, DC) can't be selected. 

![image](https://user-images.githubusercontent.com/673511/48639142-afe72380-e9a0-11e8-9df4-9e3d0ecad06a.png)

I'm guessing this is just a quirk with the SVG, but may be worth fixing so users testing this are not confused. 

_Copied from original issue: kobotoolbox/enketo-express#1128_

**Comment by enketo-issue-mover** [comment] 2019-01-02 22:58
_From @MartijnR on November 16, 2018 21:13_

Yes, indeed. Thanks.

* [ ] add IDs for Kentucky, Rhode Island (assuming there aren't any)

**Comment by MartijnR** [comment] 2019-08-08 20:37
Looks like this was fixed (maybe it was a bug in the widget because the XLSForm and SVG look correct). Only DC might be an issue still but that's likely related to its size.

**Comment by MartijnR** [comment] 2019-08-08 20:39
Ah I see, the issue is fixed in enke.to/::widgets, but not in enke.to/::imgmap

* [ ] updated imgmap demo form

**Comment by MartijnR** [comment] 2019-08-08 20:50
redeployed updated form on kc.kobotoolbox/enketo but old XForm is still being served. 

* [ ] check again later

**Closed** 2020-08-25 21:24 UTC
