### ISSUE TITLE
Data loss: not all signature images are uploaded in offline-capable forms

### ISSUE THREAD

**Issue by p2edwards** [enketo/enketo-express#339] opened 2021-10-18 19:44 UTC
**Description**

This is an intermittent bug that results in a loss of signature images.

If a form includes multiple image questions, at least one of which is `appearance: signature`, and the form is running in offline mode, it is likely that one or more of the signature image files get lost in the submission process. 

**To Reproduce**

When running a form like this in offline mode:

type | name | label | appearance
-- | -- | -- | --
start | start |   |  
end | end |   |  
image | sign_now | sign now! | signature
image | sign_again | sign again! | signature

The first or second signature image is likely to be missing, for each submission.

other factors:

- must use offline version of form to reproduce bug
- happens on 2.5.6 and 2.8.1 (about to test on 3.0.1)
- tried to sign both fields as quickly as possible
- having a non-signature appearance image in the form can also "crowd out" the signature file
but regular images do not crowd each other out based on our testing so far.

**Expected behavior**
Desired behavior is that no attachments are missing upon submission.

**Browser and OS**
 - OS: Issue has been reproduced on macos and Linux.
 - Browser: Issue has been reproduced in Chrome and Safari. 

**Additional context**

I'm looking into this now, so I can add screenshots or improved description soon.

**Comment by jnm** [comment] 2021-12-15 21:58
Hello @eyelidlessness, @MartijnR, did you all reach any consensus on the best way to proceed? The KoBo team could contribute work toward a fix, but I'd want the design direction to be clear beforehand. Thank you!

**Comment by eyelidlessness** [comment] 2021-12-15 23:43
It's been a while since I looked at my potential fix, but from my recollection I'd think it's probably a good enough band-aid, anticipating a more thoughtful solution in the longer term. I'll look into testing and preparing my solution for a PR soon.

**Comment by jnm** [comment] 2021-12-16 16:09
Thank you very much. We're also happy to help with testing and review; just let us know if we can assist in any way.

**Comment by lognaturel** [comment] 2022-01-20 04:50
@jnm Want to make sure you saw @eyelidlessness’ review request! We’re hoping to get a release out soon, ideally with this fix.

**Comment by jnm** [comment] 2022-01-20 14:59
:tada: Yes! I saw it. Thank you @eyelidlessness. Will review today or tomorrow.

**Comment by jnm** [comment] 2022-04-27 13:26
@joshuaberetta, after you mentioned that you were still seeing this bug on 3.1.0, I reproduced it as well (with a mouse, this time, not a touchscreen) and recorded a screencast:
https://user-images.githubusercontent.com/2085013/165527413-64184ccf-e7b1-44d6-919c-77fc6e74686e.mp4

I think we should test on 3.1.1 just to make sure it's still broken there, and then also test the earliest release that included #373 to see whether this problem is a regression or just something I missed by not testing thoroughly enough during my review.

After that, let's reopen this issue if needed.

**Comment by joshuaberetta** [comment] 2022-09-29 08:11
Another case in the Kobo community: https://community.kobotoolbox.org/t/problems-with-loss-of-signature-images/33825

**Comment by lognaturel** [comment] 2022-12-14 18:47
We believe this will be further addressed by https://github.com/enketo/enketo-core/pull/931, to be released shortly in 5.0.1. Please re-open if you can reproduce after that.

**Closed by lognaturel** 2022-12-14 18:47 UTC
Labels: bug, offline-only
